### PR TITLE
Create circular grating coupler 

### PR DESCRIPTION
**Pull request by gyger**
**Not to be merged yet**
I needed this grating in a chip and build the component, are you interested in integrating it? Then I would also create the cladding layer and add some documentation.

Based on Zhu et al., (2017) https://doi.org/10.1364/OE.25.033297 for SiN.

image
and here used:
image

### CODE REVIEW

**Comment by DerekK88** [comment]
I added a grating coupler class recently which should be able to generate this.  

https://picwriter.readthedocs.io/en/latest/components/gratingcouplers.html

If you pass it theta=pi, and taper_length= (1-duty_cycle)*period, it will generate the structure you showed above.

**Comment by DerekK88** [comment]
I see what you mean.  Yeah, I think that would be a good fix to the GratingCoupler class.  Why don't you make that change (either here or in a separate PR) and I'll happily merge it.

**Comment by DerekK88** [comment]
The clad part will also need updating for those extreme (>45deg) angles.  Perhaps it's best implemented as a custom polygon rather than a gdspy Path object

**Comment by gyger** [comment]
I still have some problems with the Cladding. Is it ok, that the cladding of one structure writes on top of the cladding of another structure (the incoming waveguide?).

**Comment by DerekK88** [comment]
Yes, overlaps in general are OK so long as the polygons are all individually valid (i.e. no self-intersections / self-overlaps).  They are typically removed before fab through layer merges & booleans.

I'm going to go ahead and merge the pull request even though I haven't checked the new `GratingCouplerCircular` class that you added.  If there's issues in that we can open an issue and fix it.

**Pull request merged**
