### PR TITLE
Added SWG waveguides

### PR DESCRIPTION
**Pull request by peterxsu**
The implementation of SWG waveguides has been added to the Waveguide and WaveguideTemplate classes. Note that the SWG nature will not apply across different components. Also, there's no way to guarantee perfect periodicity right now across components when connecting them together.

### CODE REVIEW

**Comment by DerekK88** [comment]
Hm, this seems to be breaking the continuous integration tests, meaning there are errors with how strip and slot waveguides are created now.  Why don't you wrap the SWG code in `waveguide.py` with:
`if self.wgt.wg_type=='swg':` (as you did at line 127), then
`else:` followed by all the old code for strip and slot waveguides (lines 110 - 157 from the original waveguide.py file).  

Right now it looks like you moved around /deleted parts of the original strip and slot waveguide creation.

**Comment by DerekK88** [comment]
Also, with the addition of SWG waveguides, it would be great to add a component to the library for converting strip to SWG waveguides (and vice-versa).

Once this I look over the code in a little more detail, I'll add nosetests for the SWG waveguides.

**Comment by peterxsu** [comment]
Do you know what the tests test for? I tried to move stuff around so that I didn't have to copy the code to make the cladding, since the cladding is identical regardless of the waveguide type.

As for the strip -> SWG and vice versa coupler, I'm assuming it'd just be a taper from the strip to a point overlapped with the SWG?

**Comment by peterxsu** [comment]
So I just reverted the changes to the entire waveguide file and tried running the DC creation test on my own computer. I'm getting the same error and the DC area I'm getting is 65615.85044895338, which is off from the expected by < 0.0002... And it's the same area that I'm getting if I run the test with my new updated file as well...

**Comment by peterxsu** [comment]
Also, just checked appveyor and the failures started after the rounding error fix, which makes a lot of sense. The rounding fix changed the areas of the resulting structures, so you'll probably need to recalibrate them all.

**Comment by peterxsu** [comment]
Just added an unrelated fix in Spiral2

**Pull request merged**
